using System;

namespace CMcG.CodeAlignment.Business
{
    [Flags]
    public enum Key
    {
        D0            = 48,
        D1            = 49,
        D2            = 50,
        D3            = 51,
        D4            = 52,
        D5            = 53,
        D6            = 54,
        D7            = 55,
        D8            = 56,
        D9            = 57,
        A             = 65,
        B             = 66,
        C             = 67,
        D             = 68,
        E             = 69,
        F             = 70,
        G             = 71,
        H             = 72,
        I             = 73,
        J             = 74,
        K             = 75,
        L             = 76,
        M             = 77,
        N             = 78,
        O             = 79,
        P             = 80,
        Q             = 81,
        R             = 82,
        S             = 83,
        T             = 84,
        U             = 85,
        V             = 86,
        W             = 87,
        X             = 88,
        Y             = 89,
        Z             = 90,
        Space         = 32,
        Multiply      = 106,
        Add           = 107,
        Subtract      = 109,
        Decimal       = 110,
        Divide        = 111,
        Semicolon     = 186,
        EqualsPlus    = 187,
        Comma         = 188,
        Minus         = 189,
        Period        = 190,
        Question      = 191,
        Tilde         = 192,
        OpenBrackets  = 219,
        Pipe          = 220,
        CloseBrackets = 221,
        Quotes        = 222,
        Backslash     = 226,
    }
}